apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - platforms-deployment.yaml
  - platforms-np-srv.yaml
  - commands-deployment.yaml
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.2.0/deploy/static/provider/cloud/deploy.yaml
  - ingress-srv.yaml
  - local-pvc.yaml
  - mssql-platform-deployment.yaml
  - mssql-commands-deployment.yaml
  - rabbitmq-deployment.yaml